<Project Sdk="Remora.Resonite.Sdk/2.3.1">
  <PropertyGroup>
    <PackageId>FlexibleContactSorting</PackageId>
    <Title>Flexible Contact Sorting</Title>
    <Authors>Banane9</Authors>
    <Version>0.8.3-beta</Version>
    <Description>This MonkeyLoader mod for Resonite allows sorting contacts flexibly and to your liking, including pinning your favorites to the top. It also adds other Quality of Life features to the Contacts Page, such as a clear button for the search, an extra color for your outgoing conctact requests, capacity display to contacts' sessions, and contacts loading without lag.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ResoniteModdingGroup/FlexibleContactsSort</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <PackageTags>mod; mods; monkeyloader; resonite; contacts</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <None Include="Locale\*" Pack="true" PackagePath="content/Locale/" />
  </ItemGroup>

  <ItemGroup>
    <ResoniteReference Include="Elements.Core" />
    <ResoniteReference Include="Elements.Assets" />
    <ResoniteReference Include="Elements.Quantity" />
    <ResoniteReference Include="FrooxEngine" />
    <ResoniteReference Include="SkyFrost.Base" />
    <ResoniteReference Include="SkyFrost.Base.Models" />
  </ItemGroup>
</Project>
